# Generated by Django 3.2.5 on 2021-12-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mprice', models.IntegerField()),
                ('mabout', models.TextField()),
                ('phonemodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='classApp.phonemodel')),
            ],
        ),
    ]
